services:
  users-server:
    hostname: $USERS_HOST
    build: ../summorist-users
    container_name: $USERS_HOST
    ports:
      - $USERS_PORT:$USERS_PORT
    env_file: .env
    restart: always
    environment:
      USERS_PRIVATE_KEY: $USERS_PRIVATE_KEY
      USERS_PUBLIC_KEY: $USERS_PUBLIC_KEY
    depends_on:
      users-db:
        condition: service_healthy
    networks:
      - smrt_net
    profiles:
      - users
      - all
      - ""

  users-db:
    image: postgres:16-alpine
    hostname: $USERS_POSTGRES_HOST
    restart: always
    shm_size: 128mb
    container_name: $USERS_POSTGRES_HOST
    environment:
      POSTGRES_USER: $USERS_POSTGRES_USER
      POSTGRES_PASSWORD: $USERS_POSTGRES_PASSWORD
      POSTGRES_HOST: $USERS_POSTGRES_HOST
      PGPORT: $USERS_POSTGRES_PORT
      POSTGRES_DB: $USERS_POSTGRES_DBNAME
    volumes:
      - users_postgres_data:/var/lib/postgresql/data
      - ../summorist-users/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $USERS_POSTGRES_USER -d $USERS_POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - smrt_net
    profiles:
      - users
      - all
      - ""

  mores-server:
    hostname: $MORES_HOST
    build: ../summorist-mores
    container_name: $MORES_HOST
    ports:
      - $MORES_PORT:$MORES_PORT
    env_file: .env
    depends_on:
       mores-db:
         condition: service_healthy
    restart: always
    networks:
      - smrt_net
    profiles:
      - mores
      - all
      - ""

  mores-db:
    image: postgres:16-alpine
    hostname: $MORES_POSTGRES_HOST
    restart: always
    shm_size: 128mb
    container_name: $MORES_POSTGRES_HOST
    environment:
      POSTGRES_USER: $MORES_POSTGRES_USER
      POSTGRES_PASSWORD: $MORES_POSTGRES_PASSWORD
      POSTGRES_HOST: $MORES_POSTGRES_HOST
      PGPORT: $MORES_POSTGRES_PORT
      POSTGRES_DB: $MORES_POSTGRES_DBNAME
    volumes:
      - mores_postgres_data:/var/lib/postgresql/data
      - ../summorist-mores/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $MORES_POSTGRES_USER -d $MORES_POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - smrt_net
    profiles:
      - mores
      - all
      - ""

networks:
  smrt_net:
    driver: bridge

volumes:
  users_postgres_data:
  mores_postgres_data:

