services:
  users-server:
    hostname: $USERS_HOST
    build: ../users
    container_name: $USERS_HOST
    ports:
      - $USERS_PORT:$USERS_PORT
    env_file: .env
    depends_on:
      users-db:
        condition: service_healthy
    networks:
      - smrt_net
    profiles:
      - users
      - all

  users-db:
    image: postgres:16-alpine
    hostname: $USERS_POSTGRES_HOST
    restart: always
    shm_size: 128mb
    container_name: $USERS_POSTGRES_HOST
    ports:
      - 5432:$USERS_POSTGRES_PORT
    environment:
      POSTGRES_USER: $USERS_POSTGRES_USER
      POSTGRES_PASSWORD: $USERS_POSTGRES_PASSWORD
      POSTGRES_HOST: $USERS_POSTGRES_HOST
      POSTGRES_PORT: $USERS_POSTGRES_PORT
      POSTGRES_DB: $USERS_POSTGRES_DBNAME
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../users/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $USERS_POSTGRES_USER -d $USERS_POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - smrt_net
    profiles:
      - users
      - all

  mores-server:
    hostname: $MORES_HOST
    build: ../mores
    container_name: $MORES_HOST
    ports:
      - $MORES_PORT:$MORES_PORT
    env_file: .env
    depends_on:
      mores-db:
        condition: service_healthy
    networks:
      - smrt_net
    profiles:
      - mores
      - all

  mores-db:
    image: postgres:16-alpine
    hostname: $MORES_POSTGRES_HOST
    restart: always
    shm_size: 128mb
    container_name: $MORES_POSTGRES_HOST
    ports:
      - $MORES_POSTGRES_PORT:$MORES_POSTGRES_PORT
    environment:
      POSTGRES_USER: $MORES_POSTGRES_USER
      POSTGRES_PASSWORD: $MORES_POSTGRES_PASSWORD
      POSTGRES_HOST: $MORES_POSTGRES_HOST
      POSTGRES_PORT: $MORES_POSTGRES_PORT
      POSTGRES_DB: $MORES_POSTGRES_DBNAME
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../users/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $USERS_POSTGRES_USER -d $USERS_POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - smrt_net
    profiles:
      - mores
      - all

networks:
  smrt_net:
    driver: bridge

volumes:
  postgres_data:

